import { eventInsertSchemaM } from "../../../db/schema/Event";
import type { CreateEvent, EventFilter } from "../../events/domain/event";
export declare const getAllEvents: () => import("drizzle-orm/mysql-core").MySqlSelectBase<"event", {
    id: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    name: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    date: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "date";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDate";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    startHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "start_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    endHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "end_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceUsed: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "space_used";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceMember: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_member";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceGuest: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_guest";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    capacity: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "capacity";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    urlImage: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "url_image";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    isActive: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "is_active";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    description: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "description";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    allowOutsiders: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "allow_outsiders";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    numberOfAssistants: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "number_of_assistants";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    reservationId: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "reservation_id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlBigInt53";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
}, "single", import("drizzle-orm/mysql2").MySql2PreparedQueryHKT, Record<"event", "not-null">, false, never, {
    id: number;
    name: string;
    date: Date;
    startHour: Date;
    endHour: Date;
    spaceUsed: string;
    ticketPriceMember: string;
    ticketPriceGuest: string | null;
    capacity: number;
    urlImage: string | null;
    isActive: boolean;
    description: string;
    allowOutsiders: boolean;
    numberOfAssistants: number;
    reservationId: number;
}[], {
    id: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    name: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    date: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "date";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDate";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    startHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "start_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    endHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "end_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceUsed: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "space_used";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceMember: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_member";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceGuest: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_guest";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    capacity: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "capacity";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    urlImage: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "url_image";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    isActive: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "is_active";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    description: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "description";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    allowOutsiders: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "allow_outsiders";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    numberOfAssistants: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "number_of_assistants";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    reservationId: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "reservation_id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlBigInt53";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
}>;
export declare const getAllEventsMember: () => import("drizzle-orm/mysql-core").MySqlSelectBase<"event", {
    id: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    name: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    date: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "date";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDate";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    startHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "start_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    endHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "end_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    allowOutsiders: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "allow_outsiders";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
}, "partial", import("drizzle-orm/mysql2").MySql2PreparedQueryHKT, Record<"event", "not-null">, false, never, {
    id: number;
    name: string;
    date: Date;
    startHour: Date;
    endHour: Date;
    allowOutsiders: boolean;
}[], {
    id: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    name: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    date: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "date";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDate";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    startHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "start_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    endHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "end_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    allowOutsiders: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "allow_outsiders";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
}>;
export declare const getEventById: (id: number) => Promise<{
    id: number;
    name: string;
    date: Date;
    startHour: Date;
    endHour: Date;
    spaceUsed: string;
    ticketPriceMember: string;
    ticketPriceGuest: string | null;
    capacity: number;
    urlImage: string | null;
    isActive: boolean;
    description: string;
    allowOutsiders: boolean;
    numberOfAssistants: number;
    reservationId: number;
}>;
export declare const createEvent: (data: unknown) => Promise<{
    id: number;
    name: string;
    date: Date;
    startHour: Date;
    endHour: Date;
    spaceUsed: string;
    ticketPriceMember: string;
    ticketPriceGuest: string | null;
    capacity: number;
    urlImage: string | null;
    isActive: boolean;
    description: string;
    allowOutsiders: boolean;
    numberOfAssistants: number;
    reservationId: number;
}>;
export declare const updateEvent: (id: number, data: Partial<CreateEvent>) => Promise<{
    id: number;
    name: string;
    date: Date;
    startHour: Date;
    endHour: Date;
    spaceUsed: string;
    ticketPriceMember: string;
    ticketPriceGuest: string | null;
    capacity: number;
    urlImage: string | null;
    isActive: boolean;
    description: string;
    allowOutsiders: boolean;
    numberOfAssistants: number;
    reservationId: number;
}>;
export declare const getFilteredPaginated: (filter: EventFilter) => Promise<{
    eventos: {
        id: number;
        name: string;
        date: Date;
        startHour: Date;
        endHour: Date;
        spaceUsed: string;
        ticketPriceMember: string;
        ticketPriceGuest: string | null;
        capacity: number;
        urlImage: string | null;
        isActive: boolean;
        description: string;
        allowOutsiders: boolean;
        numberOfAssistants: number;
        reservationId: number;
    }[];
    totalPages: number;
}>;
import { reservationInsertSchema } from "../../../db/schema/Reservation";
export declare const createNewEvent: (dataReservation: typeof reservationInsertSchema._input, dataEvent: typeof eventInsertSchemaM._input) => Promise<{
    reservationInsertId: number;
    eventInsertId: number;
}>;
export declare const getAllEventsSpace: () => Omit<import("drizzle-orm/mysql-core").MySqlSelectBase<"event", {
    id: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    name: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    date: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "date";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDate";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    startHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "start_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    endHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "end_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceUsed: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "space_used";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceMember: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_member";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceGuest: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_guest";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    capacity: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "capacity";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    urlImage: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "url_image";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    isActive: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "is_active";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    description: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "description";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    allowOutsiders: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "allow_outsiders";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    numberOfAssistants: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "number_of_assistants";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    reservationId: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "reservation_id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlBigInt53";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceId: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "space";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceName: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "space";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
}, "partial", import("drizzle-orm/mysql2").MySql2PreparedQueryHKT, Record<"event", "not-null"> & {
    reservation: "not-null";
} & {
    space: "not-null";
}, false, never, {
    id: number;
    name: string;
    date: Date;
    startHour: Date;
    endHour: Date;
    spaceUsed: string;
    ticketPriceMember: string;
    ticketPriceGuest: string | null;
    capacity: number;
    urlImage: string | null;
    isActive: boolean;
    description: string;
    allowOutsiders: boolean;
    numberOfAssistants: number;
    reservationId: number;
    spaceId: number;
    spaceName: string;
}[], {
    id: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    name: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    date: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "date";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDate";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    startHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "start_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    endHour: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "end_hour";
        tableName: "event";
        dataType: "date";
        columnType: "MySqlDateTime";
        data: Date;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceUsed: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "space_used";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceMember: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_member";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    ticketPriceGuest: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "ticket_price_guest";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlDecimal";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    capacity: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "capacity";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    urlImage: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "url_image";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    isActive: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "is_active";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    description: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "description";
        tableName: "event";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    allowOutsiders: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "allow_outsiders";
        tableName: "event";
        dataType: "boolean";
        columnType: "MySqlBoolean";
        data: boolean;
        driverParam: number | boolean;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    numberOfAssistants: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "number_of_assistants";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlInt";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    reservationId: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "reservation_id";
        tableName: "event";
        dataType: "number";
        columnType: "MySqlBigInt53";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceId: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "id";
        tableName: "space";
        dataType: "number";
        columnType: "MySqlSerial";
        data: number;
        driverParam: number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: true;
        isAutoincrement: true;
        hasRuntimeDefault: false;
        enumValues: undefined;
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
    spaceName: import("drizzle-orm/mysql-core").MySqlColumn<{
        name: "name";
        tableName: "space";
        dataType: "string";
        columnType: "MySqlVarChar";
        data: string;
        driverParam: string | number;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: [string, ...string[]];
        baseColumn: never;
        identity: undefined;
        generated: undefined;
    }, {}, {}>;
}>, never>;
export declare const getAllInscriptions: (idEvento: number) => Promise<{
    eventInscriptionId: number;
    nombre: string;
    apellido: string;
    fechaPago: Date;
    dni: string | null;
}[]>;
export declare const deleteEventInscription: (id: number) => Omit<import("drizzle-orm/mysql-core").MySqlUpdateBase<import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "event_inscription";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "event_inscription";
            dataType: "number";
            columnType: "MySqlSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: true;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        assisted: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "assisted";
            tableName: "event_inscription";
            dataType: "boolean";
            columnType: "MySqlBoolean";
            data: boolean;
            driverParam: number | boolean;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isCancelled: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "is_cancelled";
            tableName: "event_inscription";
            dataType: "boolean";
            columnType: "MySqlBoolean";
            data: boolean;
            driverParam: number | boolean;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        eventId: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "events_id";
            tableName: "event_inscription";
            dataType: "number";
            columnType: "MySqlBigInt53";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        inscriptionXUser: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "inscription_x_user";
            tableName: "event_inscription";
            dataType: "number";
            columnType: "MySqlBigInt53";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "mysql";
}>, import("drizzle-orm/mysql2").MySql2QueryResultHKT, import("drizzle-orm/mysql2").MySql2PreparedQueryHKT, false, "where">, "where">;
